const countries: { countryCode: string; label: string }[] = [
  { countryCode: "ar", label: "Argentina" },
  { countryCode: "au", label: "Australia" },
  { countryCode: "at", label: "Austria" },
  { countryCode: "be", label: "Belgium" },
  { countryCode: "br", label: "Brazil" },
  { countryCode: "bg", label: "Bulgaria" },
  { countryCode: "ca", label: "Canada" },
  { countryCode: "cn", label: "China" },
  { countryCode: "co", label: "Colombia" },
  { countryCode: "cu", label: "Cuba" },
  { countryCode: "cz", label: "Czech Republic" },
  { countryCode: "eg", label: "Egypt" },
  { countryCode: "fr", label: "France" },
  { countryCode: "de", label: "Germany" },
  { countryCode: "gr", label: "Greece" },
  { countryCode: "hk", label: "Hong Kong" },
  { countryCode: "hu", label: "Hungary" },
  { countryCode: "in", label: "India" },
  { countryCode: "id", label: "Indonesia" },
  { countryCode: "ie", label: "Ireland" },
  { countryCode: "il", label: "Israel" },
  { countryCode: "it", label: "Italy" },
  { countryCode: "jp", label: "Japan" },
  { countryCode: "lv", label: "Latvia" },
  { countryCode: "lt", label: "Lithuania" },
  { countryCode: "my", label: "Malaysia" },
  { countryCode: "mx", label: "Mexico" },
  { countryCode: "ma", label: "Morocco" },
  { countryCode: "nl", label: "Netherlands" },
  { countryCode: "nz", label: "New Zealand" },
  { countryCode: "ng", label: "Nigeria" },
  { countryCode: "no", label: "Norway" },
  { countryCode: "ph", label: "Philippines" },
  { countryCode: "pl", label: "Poland" },
  { countryCode: "pt", label: "Portugal" },
  { countryCode: "ro", label: "Romania" },
  { countryCode: "ru", label: "Russia" },
  { countryCode: "sa", label: "Saudi Arabia" },
  { countryCode: "rs", label: "Serbia" },
  { countryCode: "sg", label: "Singapore" },
  { countryCode: "sk", label: "Slovakia" },
  { countryCode: "si", label: "Slovenia" },
  { countryCode: "za", label: "South Africa" },
  { countryCode: "kr", label: "South Korea" },
  { countryCode: "se", label: "Sweden" },
  { countryCode: "ch", label: "Switzerland" },
  { countryCode: "tw", label: "Taiwan" },
  { countryCode: "th", label: "Thailand" },
  { countryCode: "tr", label: "Turkey" },
  { countryCode: "ae", label: "UAE" },
  { countryCode: "ua", label: "Ukraine" },
  { countryCode: "gb", label: "United Kingdom" },
  { countryCode: "us", label: "United States" },
  { countryCode: "ve", label: "Venezuela" },
];
export default countries;
