const countries: { country: string; label: string }[] = [
  { country: "ar", label: "Argentina" },
  { country: "au", label: "Australia" },
  { country: "at", label: "Austria" },
  { country: "be", label: "Belgium" },
  { country: "br", label: "Brazil" },
  { country: "bg", label: "Bulgaria" },
  { country: "ca", label: "Canada" },
  { country: "cn", label: "China" },
  { country: "co", label: "Colombia" },
  { country: "cu", label: "Cuba" },
  { country: "cz", label: "Czech Republic" },
  { country: "eg", label: "Egypt" },
  { country: "fr", label: "France" },
  { country: "de", label: "Germany" },
  { country: "gr", label: "Greece" },
  { country: "hk", label: "Hong Kong" },
  { country: "hu", label: "Hungary" },
  { country: "in", label: "India" },
  { country: "id", label: "Indonesia" },
  { country: "ie", label: "Ireland" },
  { country: "il", label: "Israel" },
  { country: "it", label: "Italy" },
  { country: "jp", label: "Japan" },
  { country: "lv", label: "Latvia" },
  { country: "lt", label: "Lithuania" },
  { country: "my", label: "Malaysia" },
  { country: "mx", label: "Mexico" },
  { country: "ma", label: "Morocco" },
  { country: "nl", label: "Netherlands" },
  { country: "nz", label: "New Zealand" },
  { country: "ng", label: "Nigeria" },
  { country: "no", label: "Norway" },
  { country: "ph", label: "Philippines" },
  { country: "pl", label: "Poland" },
  { country: "pt", label: "Portugal" },
  { country: "ro", label: "Romania" },
  { country: "ru", label: "Russia" },
  { country: "sa", label: "Saudi Arabia" },
  { country: "rs", label: "Serbia" },
  { country: "sg", label: "Singapore" },
  { country: "sk", label: "Slovakia" },
  { country: "si", label: "Slovenia" },
  { country: "za", label: "South Africa" },
  { country: "kr", label: "South Korea" },
  { country: "se", label: "Sweden" },
  { country: "ch", label: "Switzerland" },
  { country: "tw", label: "Taiwan" },
  { country: "th", label: "Thailand" },
  { country: "tr", label: "Turkey" },
  { country: "ae", label: "UAE" },
  { country: "ua", label: "Ukraine" },
  { country: "gb", label: "United Kingdom" },
  { country: "us", label: "United States" },
  { country: "ve", label: "Venezuela" },
];
export default countries;
